// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1ViXeovAcQU0F7Ghioj_xmzPXkQA3rO0',
    appId: '1:122663162867:web:c09d050086ab0404acb886',
    messagingSenderId: '122663162867',
    projectId: 'sheshieldai-63fb7',
    authDomain: 'sheshieldai-63fb7.firebaseapp.com',
    storageBucket: 'sheshieldai-63fb7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqwlqJTlzYIyqgbicfunKF1vRXaaGkllM',
    appId: '1:122663162867:android:f5efd14d4edbbc0cacb886',
    messagingSenderId: '122663162867',
    projectId: 'sheshieldai-63fb7',
    storageBucket: 'sheshieldai-63fb7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIkQ2zpZbOsh06QMGXq1fzvau1BypsMmU',
    appId: '1:122663162867:ios:4a0ae69e97c15ee9acb886',
    messagingSenderId: '122663162867',
    projectId: 'sheshieldai-63fb7',
    storageBucket: 'sheshieldai-63fb7.firebasestorage.app',
    iosBundleId: 'com.projectforge.projectforgeAi',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIkQ2zpZbOsh06QMGXq1fzvau1BypsMmU',
    appId: '1:122663162867:ios:4a0ae69e97c15ee9acb886',
    messagingSenderId: '122663162867',
    projectId: 'sheshieldai-63fb7',
    storageBucket: 'sheshieldai-63fb7.firebasestorage.app',
    iosBundleId: 'com.projectforge.projectforgeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1ViXeovAcQU0F7Ghioj_xmzPXkQA3rO0',
    appId: '1:122663162867:web:36d2a6cc55740a77acb886',
    messagingSenderId: '122663162867',
    projectId: 'sheshieldai-63fb7',
    authDomain: 'sheshieldai-63fb7.firebaseapp.com',
    storageBucket: 'sheshieldai-63fb7.firebasestorage.app',
  );
}
